### PR TITLE
Clean_up_list_of_dependencies

### PR DESCRIPTION
**Pull request by VOSpdUkraine**

### CODE REVIEW

**Review by dawidgil — APPROVED** [review]
What about:
- fullcalendar
- jquery
- lodash
- popper
? Did you check them?

**Comment by VOSpdUkraine** [comment]
What about:

fullcalendar
jquery
lodash
popper
? Did you check them?

yes i checked them they are used in different places of our project

**Comment by dawidgil** [comment]
Strange, because lodash as far as i remember was used in directive which wasn't used in application. In other words we could remove directive and then remove lodash. Did you check it this way?

**Comment by VOSpdUkraine** [comment]
image

**Comment by dawidgil** [comment]
Ok, so i dig a little bit and i see that sidebar is not used in application. It's commented out, so after a quick talk with @davycastillo i think we can remove also sidebar. 
I think we should remove dead code.

**Review by davycastillo — APPROVED** [review]

**Pull request merged**
